export interface Tool {
  id: string;
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  icon: string;
  color: 'yellow' | 'blue' | 'red' | 'purple' | 'green' | 'orange';
  tag: string;
  accentColor: string;
  bgColor: string;
  borderColor: string;
  textColor: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  processing: 'browser' | 'server' | 'hybrid';
}

export const TOOLS: Tool[] = [
  {
    id: 'merge',
    slug: 'merge',
    name: 'Merge PDFs',
    description: 'Combine multiple PDF files into a single document. Drag to reorder.',
    longDescription: 'Effortlessly combine any number of PDF files into one document. Drag and drop to reorder pages before merging. Supports any number of files.',
    icon: '🔗',
    color: 'blue',
    tag: 'Popular',
    accentColor: '#47b8ff',
    bgColor: 'rgba(71,184,255,0.08)',
    borderColor: 'rgba(71,184,255,0.2)',
    textColor: '#47b8ff',
    metaTitle: 'Merge PDF Files Online Free — Combine PDFs in Seconds',
    metaDescription: 'Merge multiple PDF files into one document online for free. No sign up required. Drag to reorder files before merging. 100% private — processed in your browser.',
    keywords: ['merge pdf', 'combine pdf', 'merge pdf online free', 'join pdf files'],
    processing: 'browser',
  },
  {
    id: 'split',
    slug: 'split',
    name: 'Split PDF',
    description: 'Extract specific pages or split by ranges into separate PDFs.',
    longDescription: 'Split a PDF into multiple files by page range, every N pages, or individual pages. Downloads as a ZIP archive.',
    icon: '✂️',
    color: 'green',
    tag: 'Editing',
    accentColor: '#47ffb8',
    bgColor: 'rgba(71,255,184,0.08)',
    borderColor: 'rgba(71,255,184,0.2)',
    textColor: '#47ffb8',
    metaTitle: 'Split PDF Online Free — Extract Pages from PDF',
    metaDescription: 'Split a PDF into multiple files or extract specific pages online for free. By range, every N pages, or individual pages. No upload required.',
    keywords: ['split pdf', 'extract pages from pdf', 'split pdf online', 'pdf page extractor'],
    processing: 'browser',
  },
  {
    id: 'compress',
    slug: 'compress',
    name: 'Compress PDF',
    description: 'Reduce PDF file size with server-side Ghostscript compression.',
    longDescription: 'Achieve real file size reduction using server-side Ghostscript compression. Choose between screen, ebook, printer, and prepress quality.',
    icon: '📦',
    color: 'orange',
    tag: 'Optimize',
    accentColor: '#ffa547',
    bgColor: 'rgba(255,165,71,0.08)',
    borderColor: 'rgba(255,165,71,0.2)',
    textColor: '#ffa547',
    metaTitle: 'Compress PDF Online Free — Reduce PDF File Size',
    metaDescription: 'Compress PDF files online for free with up to 80% size reduction. Uses Ghostscript for real compression. Choose quality level. No sign up needed.',
    keywords: ['compress pdf', 'reduce pdf size', 'pdf compressor', 'compress pdf online free', 'shrink pdf'],
    processing: 'server',
  },
  {
    id: 'watermark',
    slug: 'watermark',
    name: 'Add Watermark',
    description: 'Protect documents with custom text watermarks — full control.',
    longDescription: 'Add custom text watermarks to every page of your PDF. Control position, opacity, rotation, font size, and color.',
    icon: '🔏',
    color: 'yellow',
    tag: 'Security',
    accentColor: '#e8ff47',
    bgColor: 'rgba(232,255,71,0.08)',
    borderColor: 'rgba(232,255,71,0.2)',
    textColor: '#e8ff47',
    metaTitle: 'Add Watermark to PDF Online Free',
    metaDescription: 'Add custom text watermarks to PDF files online for free. Control text, color, opacity, angle, and position. Instant download. No uploads to server.',
    keywords: ['add watermark to pdf', 'pdf watermark', 'watermark pdf online', 'stamp pdf'],
    processing: 'browser',
  },
  {
    id: 'rotate',
    slug: 'rotate',
    name: 'Rotate PDF',
    description: 'Rotate all, even, odd, or specific pages to the correct orientation.',
    longDescription: 'Rotate PDF pages by 90°, 180°, or 270°. Apply to all pages, even/odd pages only, or a custom selection.',
    icon: '🔄',
    color: 'blue',
    tag: 'Editing',
    accentColor: '#47b8ff',
    bgColor: 'rgba(71,184,255,0.08)',
    borderColor: 'rgba(71,184,255,0.2)',
    textColor: '#47b8ff',
    metaTitle: 'Rotate PDF Pages Online Free',
    metaDescription: 'Rotate PDF pages online for free. Rotate all, even, odd, or specific pages by 90°, 180°, or 270°. Instant download.',
    keywords: ['rotate pdf', 'rotate pdf pages', 'pdf rotation', 'flip pdf pages'],
    processing: 'browser',
  },
  {
    id: 'protect',
    slug: 'protect',
    name: 'Protect PDF',
    description: 'Password-protect your PDF with server-side AES-256 encryption.',
    longDescription: 'Add strong AES-256 password protection to your PDFs using server-side processing with qpdf. Much stronger than browser-only options.',
    icon: '🔒',
    color: 'purple',
    tag: 'Security',
    accentColor: '#b847ff',
    bgColor: 'rgba(184,71,255,0.08)',
    borderColor: 'rgba(184,71,255,0.2)',
    textColor: '#b847ff',
    metaTitle: 'Password Protect PDF Online Free — AES-256 Encryption',
    metaDescription: 'Add strong password protection to PDF files online for free. Uses AES-256 encryption via qpdf. Set user and owner passwords. No sign up required.',
    keywords: ['password protect pdf', 'encrypt pdf', 'pdf password', 'secure pdf online'],
    processing: 'server',
  },
  {
    id: 'unlock',
    slug: 'unlock',
    name: 'Unlock PDF',
    description: 'Remove password protection from PDFs you legally own.',
    longDescription: 'Remove password protection from PDF files you have the rights to access. Enter the current password to unlock and download a restriction-free copy.',
    icon: '🔓',
    color: 'red',
    tag: 'Access',
    accentColor: '#ff6b6b',
    bgColor: 'rgba(255,107,107,0.08)',
    borderColor: 'rgba(255,107,107,0.2)',
    textColor: '#ff6b6b',
    metaTitle: 'Unlock PDF Online Free — Remove PDF Password',
    metaDescription: 'Remove password protection from PDF files online for free. You must know the current password. Unlock your own PDFs instantly.',
    keywords: ['unlock pdf', 'remove pdf password', 'pdf unlocker', 'decrypt pdf'],
    processing: 'server',
  },
  {
    id: 'page-numbers',
    slug: 'page-numbers',
    name: 'Add Page Numbers',
    description: 'Insert auto-incrementing page numbers with full style control.',
    longDescription: 'Add professional page numbers to your PDF. Choose from multiple positions, formats, and styles. Skip the first N pages (e.g., cover).',
    icon: '🔢',
    color: 'yellow',
    tag: 'Format',
    accentColor: '#e8ff47',
    bgColor: 'rgba(232,255,71,0.08)',
    borderColor: 'rgba(232,255,71,0.2)',
    textColor: '#e8ff47',
    metaTitle: 'Add Page Numbers to PDF Online Free',
    metaDescription: 'Add page numbers to PDF files online for free. Choose position, format, starting number, and style. Instant download. No uploads.',
    keywords: ['add page numbers to pdf', 'pdf page numbering', 'number pdf pages'],
    processing: 'browser',
  },
  {
    id: 'sign',
    slug: 'sign',
    name: 'Sign PDF',
    description: 'Draw or type your signature and embed it into any PDF page.',
    longDescription: 'Draw your signature on the canvas or type your name and embed it directly into your PDF. Choose position and page. No registration required.',
    icon: '✍️',
    color: 'green',
    tag: 'Sign',
    accentColor: '#47ffb8',
    bgColor: 'rgba(71,255,184,0.08)',
    borderColor: 'rgba(71,255,184,0.2)',
    textColor: '#47ffb8',
    metaTitle: 'Sign PDF Online Free — Draw or Type Signature',
    metaDescription: 'Sign PDF documents online for free. Draw or type your signature and embed it on any page. Secure, private, no account needed.',
    keywords: ['sign pdf online', 'pdf signature', 'electronic signature pdf', 'esign pdf free'],
    processing: 'browser',
  },
  {
    id: 'annotate',
    slug: 'annotate',
    name: 'Annotate PDF',
    description: 'Add text boxes and sticky-note style comments to any PDF page.',
    longDescription: 'Add text annotations with custom colors and backgrounds to any page of your PDF. Great for feedback, review, and markup.',
    icon: '📝',
    color: 'orange',
    tag: 'Markup',
    accentColor: '#ffa547',
    bgColor: 'rgba(255,165,71,0.08)',
    borderColor: 'rgba(255,165,71,0.2)',
    textColor: '#ffa547',
    metaTitle: 'Annotate PDF Online Free — Add Text & Comments',
    metaDescription: 'Add text annotations, comments, and sticky notes to PDF files online for free. Choose colors and position. Instant download.',
    keywords: ['annotate pdf', 'add text to pdf', 'pdf annotation', 'comment on pdf'],
    processing: 'browser',
  },
  {
    id: 'reorder',
    slug: 'reorder',
    name: 'Reorder Pages',
    description: 'Rearrange pages by specifying any custom order you need.',
    longDescription: 'Reorder PDF pages by specifying the new page sequence. Useful for rearranging documents, moving chapters, or reversing page order.',
    icon: '↕️',
    color: 'red',
    tag: 'Editing',
    accentColor: '#ff6b6b',
    bgColor: 'rgba(255,107,107,0.08)',
    borderColor: 'rgba(255,107,107,0.2)',
    textColor: '#ff6b6b',
    metaTitle: 'Reorder PDF Pages Online Free',
    metaDescription: 'Rearrange PDF pages online for free. Specify any custom page order. Instant download. No uploads to server required.',
    keywords: ['reorder pdf pages', 'rearrange pdf pages', 'change pdf page order'],
    processing: 'browser',
  },
  {
    id: 'remove-watermark',
    slug: 'remove-watermark',
    name: 'Remove Watermark',
    description: 'Strip text watermarks by keyword, rasterize, or cover badge overlays.',
    longDescription: '3-method watermark removal: text filter for programmatic watermarks, full rasterize via server-side PDF rendering, or cover badge for Gamma/Canva stamps.',
    icon: '🚫',
    color: 'red',
    tag: 'Popular',
    accentColor: '#ff6b6b',
    bgColor: 'rgba(255,107,107,0.08)',
    borderColor: 'rgba(255,107,107,0.2)',
    textColor: '#ff6b6b',
    metaTitle: 'Remove Watermark from PDF Online Free',
    metaDescription: 'Remove watermarks from PDF files online for free. Text filter, rasterize, or cover badge methods. Works on Gamma, Canva, and custom watermarks.',
    keywords: ['remove watermark from pdf', 'pdf watermark remover', 'remove pdf stamp', 'delete watermark pdf'],
    processing: 'hybrid',
  },
  {
    id: 'decorate',
    slug: 'decorate',
    name: 'Decorate PDF',
    description: 'Add branded headers, footers, and colored page borders.',
    longDescription: 'Brand your PDF documents with custom colored header bars, footer bars, and decorative page borders. Add text labels with full color control.',
    icon: '✨',
    color: 'purple',
    tag: 'Creative',
    accentColor: '#b847ff',
    bgColor: 'rgba(184,71,255,0.08)',
    borderColor: 'rgba(184,71,255,0.2)',
    textColor: '#b847ff',
    metaTitle: 'Decorate PDF Online Free — Add Headers, Footers & Borders',
    metaDescription: 'Add branded headers, footers, and borders to PDF files online for free. Custom colors and text. Instant download.',
    keywords: ['add header to pdf', 'add footer to pdf', 'pdf decoration', 'brand pdf'],
    processing: 'browser',
  },
];

export const TOOL_MAP = Object.fromEntries(TOOLS.map(t => [t.slug, t]));

export const COLOR_CONFIG = {
  yellow: { bg: 'rgba(232,255,71,0.08)', border: 'rgba(232,255,71,0.2)', text: '#e8ff47', glow: 'rgba(232,255,71,0.35)', hover: 'rgba(232,255,71,0.06)' },
  blue:   { bg: 'rgba(71,184,255,0.08)', border: 'rgba(71,184,255,0.2)', text: '#47b8ff', glow: 'rgba(71,184,255,0.35)', hover: 'rgba(71,184,255,0.06)' },
  red:    { bg: 'rgba(255,107,107,0.08)', border: 'rgba(255,107,107,0.2)', text: '#ff6b6b', glow: 'rgba(255,107,107,0.35)', hover: 'rgba(255,107,107,0.06)' },
  purple: { bg: 'rgba(184,71,255,0.08)', border: 'rgba(184,71,255,0.2)', text: '#b847ff', glow: 'rgba(184,71,255,0.35)', hover: 'rgba(184,71,255,0.06)' },
  green:  { bg: 'rgba(71,255,184,0.08)', border: 'rgba(71,255,184,0.2)', text: '#47ffb8', glow: 'rgba(71,255,184,0.35)', hover: 'rgba(71,255,184,0.06)' },
  orange: { bg: 'rgba(255,165,71,0.08)', border: 'rgba(255,165,71,0.2)', text: '#ffa547', glow: 'rgba(255,165,71,0.35)', hover: 'rgba(255,165,71,0.06)' },
};
